#+title: MY Transition from Dev to Manager by Scott Mascio
#+roam_tags: cmm

These are questions/notes for Scott Mascio's presentation: "/MY Transition from Dev to Manager/"

* Questions
** Is being an EM for you? Consider…
   - Would age at all be a factor in one's decision to transition into management?
     There's some evidence - and one can read various articles about this - that there is
     age discrimination in the tech industry, esp. in tech roles. For example, as one approaches
     age 50 and finds oneself in the unfortunate position of having to find work as
     a software developer, despite the many years of experience that one might have,
     it would seem possible that older age becomes a liability somehow.

     So could one's age be a possible motivation here to transition to management as
     a kind of job security? That would be assuming the age issue is kind of
     inverted for management; and that in management old age meaning having a great deal
     of profession experience would be considered an asset.
   - Followup Question: Is there a prerequisite amount of professional experience that one
     should have first before considering management?
*** Resources
        [[https://bdtechtalks.com/2019/03/29/ageism-in-tech-age-limit-software-developers-face/][Ageism in tech age limit software developers face]] 


