:PROPERTIES:
:ID:       46b8f663-2c55-4540-b07f-797779c53547
:END:
#+title: Astrophotography
#+date: 2021-12-03 22:39 PM
#+updated: 2022-04-22 21:27 PM
#+filetags: :astronomy:

I use Linux, so if not mentioned specifically below, any instructions will be
for Linux (Ubuntu/Pop_os distro).

* Software
** AutoStakkert
   https://www.autostakkert.com/
   For Stacking. Windows only but runs fine using [[id:284b93d5-e030-4c8a-932b-03858767dfb6][Wine]].
*** Guides
    https://www.youtube.com/watch?v=Ci_aMmO4DBA

** DeepSkyStacker
   http://deepskystacker.free.fr/english/index.html

** FireCapture
   http://www.firecapture.de/

   For capturing. There is a Linux version that supports a limited set of
   cameras.

** KStars
   https://edu.kde.org/kstars/

   Linux, Windows and MacOS versions.

   To install this for Ubuntu/Pop_os follow [[https://www.indilib.org/get-indi/download-ubuntu.html][these instructions]]. Yes, you'll need
   ~kstars-bleeding~.

   Full featured astronomy software. Free and open source. Includes Ekos
   astrophotography suite. Apparently it can control many different devices as
   long as they have an [[https://indilib.org/][INDI]] driver. 

   If a device doesn't have an INDI driver, it is possible to make one.
   See [[https://www.indilib.org/developers/deveioper-manual.html][INDI developer guide]].

   See also [[https://docs.kde.org/trunk5/en/kstars/kstars/][Kstarts handbook]]

*** Ekos
    Part of Kstars and can control stuff like mounts, cameras, etc. It will need
    INDI to be installed with 3rd party drivers. See also
    https://www.indilib.org/get-indi/download-ubuntu.html (Follow steps 1 and
    2).

    See [[https://docs.kde.org/trunk5/en/kstars/kstars/tool-ekos.html#ekos-setup][Ekos setup instructions]]

    To run Ekos just start kstars from the terminal ~kstars~ and click the
    ~ekos~ button

** INDI
   https://indilib.org/
*** UVC Web Cameras Driver
    This is used for Celestron NexImage cameras
    https://www.indilib.org/ccds/web-cameras.html

** Oacapture
   https://www.openastroproject.org/oacapture/
   Getting this to work on Pop OS 20.10 was interesting, but it did work. I was
   able to capture images and video with my Nextimage 10.
   
   Followed this
   https://indilib.org/forum/general/6290-indi1-8-2-conflict-with-oacapture1-6-0.html#48034

   See also https://indilib.org/forum/ccds-dslrs/8422-segfault-with-neximage-10-ccd-on-linux-mint-20.html#64774
   
** PIPP
   https://sites.google.com/site/astropipp/home
   
   Used for pre-processing images/videos before stacking them. It's a Windows
   application but there are instructions for [[https://sites.google.com/site/astropipp/downloads/installing-pipp-on-linux-with-wine][installing on Linux with Wine]].
   
** RegiStax6
   http://www.astronomie.be/registax/

   Stacking and image processing. It seems like the recommendation is to use
   [[https://www.autostakkert.com/][AutoStakkert]] for stacking and RegiStax for image processing (eg, wavelet
   processing).
   
* Resources
  http://planetaryimagingtutorials.com/

* Hardware
** Eyepieces
   See also [[https://agenaastro.com/articles/guides/choosing-eyepieces-for-your-telescope.html][this advice for chosing an eyepiece]]
*** Magnification
    Magnification = Objective Focal Length / Eyepiece Focal Length
*** True Field of View
    TFOV = AFOV (apparent field of view) / Magnification
** StarSense Explorer DX 130AZ
   [[https://www.celestron.com/products/starsense-explorer-dx-130az#specifications][Specifications]]
   - Reflector
** Cameras
   https://www.celestron.com/products/neximage-10-solar-system-color-imager#specifications
