#+title: Org-roam Cheatsheet
#+roam_alias: "Org-roam stuff"
#+roam_tags: org-roam org-mode emacs
#+roam_key: "https://foo.com"


[[https://www.orgroam.com/manual.html][Org-roam online manual]]
See also [[file:20210326124530-org_mode_basics.org][Org-mode basics]]   

* Settings

  You can define these anywhere, but it makes sense to define them at the top
  along with the Org-mode [[file:20210214104302-org_mode_export_settings.org][Export Settings]]. See example in this file.

  - ~roam_alias~ is a title alias. Useful when finding files.
  - ~roam_tags~ is for categorization. Also useful when finding files.
  - ~roam_key~ is a reference. Shows notes with that reference as a link in the
    backlinks buffer.


* Capture Templates

  Example with two templates.

  #+begin_src elisp
    (setq org-roam-capture-templates
          '(("d" "default" plain #'org-roam-capture--get-point "%?" :file-name "%<%Y%m%d%H%M%S>-${slug}" :head "#+title: ${title}\n" :unnarrowed t)
            ("t" "test" plain #'org-roam-capture--get-point "%?" :file-name "%<%Y%m%d%H%M%S>-${slug}" :head "#+title: ${title}\n" :unnarrowed t)))
  #+end_src

  - ~%^{Input}~ to ask for "Input" value when initiating the capture.
  - ~%i~ Active region when capture was called.
  - [[https://orgmode.org/manual/Template-expansion.html#Template-expansion][Org-mode template expansion docs]]

* Linking Notes
  - ~org-roam-insert~
    
  One cool trick is to link to a heading in a note. After the filename add
  ~::*Header Name~.

  #+begin_src
    [[file:note.org::*My heading][Note - My Heading]] 
  #+end_src
