:PROPERTIES:
:ID:       1E969F0A-52A6-4D2C-A227-5BF6AE253044
:END:
#+title: Hotwire rails
#+date: 2021-08-21 17:11 PM
#+updated: 2023-11-26 12:21 PM
#+filetags: :javascript:ruby:rails:

* What is this?
  [[https://hotwired.dev/][Hotwire]] is a way of building web applications that, at its core, is about
  sending server rendered HTML over "this wire" (ie, HTTP or websocket). It is
  composed of three things:

  1. [[https://turbo.hotwired.dev/][Turbo]]: This is really the main thing. With this library alone, we can do
     HTML over the wire.
  2. [[https://stimulus.hotwired.dev/][Stimulus]]: A JS framework that doesn't care about rendering stuff, but
     rather with dynamic behavior typical of an SPA.
  3. Strada: something to do with mobile -- not sure. As now this moment it has
     not been made public

  See https://github.com/hotwired for all the libraries.

* Add to Rails application
  Add the ~hotwire-rails~ gem. Follow the instructions in the [[https://github.com/hotwired/hotwire-rails][Readme]].

  NOTE:
  - This appears to basically be a wrapper for [[https://github.com/hotwired/turbo-rails][turbo-rails]] and
    [[https://github.com/hotwired/stimulus-rails][stimulus-rails]].
  - The ~hotwire:install~ rake task will ~yarn add~ both NPM packages
    ~@hotwired/turbo-rails~ and ~stimulus~.
** Rails 7
   By default Rails 7 will use import maps. Consider also using [[https://esbuild.github.io/][esbuild]]. See
   also [[https://github.com/rails/jsbundling-rails][jsbundling-rails]] and [[https://www.youtube.com/watch?v=qOptalp8zUY][GoRails How to use ESBuild...]]
*** esbuild
    #+begin_src shell
      rails new foo --javascript=esbuild --css=bootstrap
    #+end_src
**** bin/dev
     Rails apps are now started with ~bin/dev~ for development. This uses [[https://github.com/ddollar/foreman][foreman]]
     to manager three processes defined in ~Procfile.dev~
     #+begin_src shell
       web: unset PORT && bin/rails server -p 3000 -b '0.0.0.0'
       js: yarn build --watch
       css: yarn build:css --watch
     #+end_src
**** package.json
     Defines two build commands:
     #+begin_src json
       "scripts": {
         "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets",
         "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules"
       }
     #+end_src
* Turbo
** Concepts
*** Turbo links
    Intercept the request from a clicked link. Remake the request using ~fetch~
    and replace the ~body~ element as opposed to a page reload.
*** Turbo frames
    Same thing as turbo links, but updates are applied to only sections of the
    dom defined with ~<turbo-frame>~ elements.
*** Turbo streams
    More control over how the DOM is updated. HTML can be appended, updated,
    removed ...etc. See also [[id:a9825c81-8f3b-42f7-acb8-f5fb4ee359b9][Turbo Streams]].
*** DOM morphing
    This is something new in Turbo 8. Morphing is a different way of updating
    the DOM. It does a diff and the new and old templates and updates the stuff
    that changed. Turbo will be using [[https://github.com/basecamp/idiomorph][idiomorph]].
    See also https://evilmartians.com/chronicles/the-future-of-full-stack-rails-turbo-morph-drive
* Tutorials
  - https://gorails.com/episodes/inline-editing-turbo-frames: Shows how to
    leverage turbo frames and rails partials to add inline field editing to a
    show page. Most of this is done in the erb view templates. See [[https://github.com/thoughtbot/hotwire-example-template/tree/hotwire-example-inline-edit][source code]]
    for an example.
* Resources
  - https://github.com/hotwired
  - https://www.honeybadger.io/blog/hotwire-rails/
  - https://github.com/thoughtbot/hotwire-example-template/tree/hotwire-example-inline-edit
  - https://gorails.com/series/hotwire-rails
  - https://blog.appsignal.com/2022/07/06/get-started-with-hotwire-in-your-ruby-on-rails-app.html
  - https://www.akshaykhot.com/using-hotwire-without-rails/ (Turbo drive and
    turbo frames without Rails)
  - https://www.akshaykhot.com/understanding-hotwire-turbo-streams/ (Turbo
    streams without Rails)
