:PROPERTIES:
:ID:       944F1F58-4EC8-444C-B7CA-787ABC19025B
:END:

#+title: New computer setup
#+date: 2021-09-23 21:22 PM
#+updated: 2025-07-16 09:11 AM
#+filetags: :shell:

A got a new laptop, a System 76 Gazelle with [[https://pop.system76.com][pop_os]]. This was the first I time
used [[https://github.com/apmiller108/dotfiles][my dotfiles]] to setup a Linux box. Previously, I always used MacOS. I want
to keep track of the setup procedure, so next time I wont have to figure some of
this shit out and maybe automate some of it too.

* Setup Git
  I need [[https://github.com/apmiller108/dotfiles][my dotfiles]] so first thing is to get git configured.
** Generate SSH key pair
    #+begin_src shell
      ssh-keygen -t ed25519 -C "Some Comment"
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/myprivatekey
    #+end_src
   Explaining of the above commands:
   1. Generate the private/pub key pair
   2. Start ~ssh-agent~
   3. Add the private key (ie, not the one with ~.pub~) to ~ssh-agent~
** Add SSH Pub key to GitHub account
  Follow [[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account][their instructions]]. But the gist of it is go to your account settings,
  add a new ssh-key and paste the contents of the ~.pub~ file.
** Clone dotfiles
** Create symlinks for git dotfiles
   With the SSH key stuff out of the way, I cloned the dotfiles repo.
   After cloning the dotfiles repo create symlinks for:
   - ~.gitconfig~
   - ~.gitignore_global~

   #+begin_src shell
     ln -s ~/dotfiles/git/gitconfig ~/.gitconfig
     ln -s ~/dotfiles/git/gitignore_global ~/.gitignore_global
   #+end_src
* Install ZSH
  #+begin_src shell
  sudo apt-get-update
  sudo apt-get install zsh
  chsh -s $(which zsh)
  sudo reboot
  #+end_src
* Install ohmyzsh
  See https://github.com/ohmyzsh/ohmyzsh
* Create symlink for dotzsh file
     #+begin_src shell
     ln -s ~/dotfiles/shell/zshrc ~/.zshrc
     #+end_src
* Install fzf
  https://github.com/junegunn/fzf
* Install npm and yarn
** Nodesource (Linux)
   https://github.com/nodesource/distributions#installation-instructions
** yarn
   #+begin_src sh
   npm install yarn -g
   #+end_src
* Install vim
** Create symlink for dotvimrc file
      #+begin_src shell
      ln -s ~/dotfiles/vim/vimrc ~/.vimrc
      #+end_src
* Install rbenv
   https://github.com/rbenv/rbenv#basic-git-checkout
** Install ruby-build
   https://github.com/rbenv/ruby-build#clone-as-rbenv-plugin-using-git
** Install a version of ruby
   #+begin_src sh
     rbenv install -l # list most recent stable versions and pick one
     rbenv install 3.2.2 # install it
     rbenv global 3.2.2 # set it to global
   #+end_src
* Install Emacs
** Download source code for the version you want
   http://mirror.us-midwest-1.nexcess.net/gnu/emacs/
   unpack it and continue...
*** Or master branch
   Clone the Emacs repo: https://git.savannah.gnu.org/git/emacs.git

   To install a certain tagged version
   - ~git tag~ to list all available tags
   - checkout the version you want: ~git checkout emacs-29.3~
** Dependencies I needed
   Run the following to determine if you have the dependencies needed and create
   the ~configure~ file
   #+begin_src sh
   CC="gcc-10" ./autogen.sh
   #+end_src

   There will probable be a lot of stuff missing. For example once...

   I needed these:
   #+begin_src shell
   sudo apt install gcc-10 libgccjit0 libgccjit-10-dev autoconf librsvg2-dev libpng-dev \
     libjpeg-dev imagemagick sqlite3 pandoc libcairo2-dev
   #+end_src

   But another time there was even more...

   See [[https://gitlab.com/mslot/src_installs/-/blob/master/emacs_install_ubuntu.sh][this]] which was helpful. After install those, I was able to move on.

** Configure and install
   Create a build directory
   #+begin_src
   mkdir build && cd build
   #+end_src
   Run ../configure with the desired build flags, whatever they mean

   To see all available build flags ~./configure --help~

   This is how I configured and installed it when I installed v28
   #+begin_src shell
   CC="gcc-10" ./configure --with-modules --with-cairo --with-imagemagick --with-rsvg --with-mailutils --with-native-compilation
   #+end_src

   And for v29:
   #+begin_src shell
   ../configure --with-native-compilation --with-json --with-xwidgets --with-imagemagick --with-rsvg CC="gcc-10"
   #+end_src

   Then install it
   #+begin_src shell
    make -j 2
    sudo make install
   #+end_src


   If using the same emacs repo from previous installs, there might be old .elc
   files from previous version installs. That will cause a problem. I'm not sure
   how to recompile them. Maybe the bootstrap command? Anyway deleting and
   re-cloning the repo works too.

   See also https://www.masteringemacs.org/article/speed-up-emacs-libjansson-native-elisp-compilation
** Add chemacs2 and profiles
   https://github.com/plexus/chemacs2

   See also [[id:4EB81167-F7EB-4C72-B62B-9FB666D2446E][Emacs profiles]]
* Install spacemacs
* Install optional tools
** rclone
   https://github.com/apmiller108/rclone
** syncthing
   https://apt.syncthing.net/
   https://docs.syncthing.net/users/autostart#using-systemd
