:PROPERTIES:
:ID:       7514BB0A-9713-4C61-9FFD-6C93BC0F0374
:ROAM_REFS: https://foo.com
:ROAM_ALIASES: "Org-roam stuff"
:END:
#+title: Org-roam
#+date: 2021-02-13 18:43 PM
#+filetags: :org_roam:org_mode:emacs:


[[https://www.orgroam.com/manual.html][Org-roam online manual]]
See also [[id:E67BF8C6-A54C-4E71-A9B3-F2FE1D14632A][Org-mode basics]]   

* V1
** Settings

   You can define these anywhere, but it makes sense to define them at the top
   along with the Org-mode [[id:EA505166-BE28-45D4-8390-343AC9B48D05][Export Settings]]. See example in this file.

   - ~roam_alias~ is a title alias. Useful when finding files.
   - ~roam_tags~ is for categorization. Also useful when finding files.
   - ~roam_key~ is a reference. Shows notes with that reference as a link in the
     backlinks buffer.

** Capture Templates

   Example with two templates.

   #+begin_src elisp
     (setq org-roam-capture-templates
           '(("d" "default" plain #'org-roam-capture--get-point "%?" :file-name "%<%Y%m%d%H%M%S>-${slug}" :head "#+title: ${title}\n" :unnarrowed t)
             ("t" "test" plain #'org-roam-capture--get-point "%?" :file-name "%<%Y%m%d%H%M%S>-${slug}" :head "#+title: ${title}\n" :unnarrowed t)))
   #+end_src

   - ~%^{Input}~ to ask for "Input" value when initiating the capture.
   - ~%i~ Active region when capture was called.
   - [[https://orgmode.org/manual/Template-expansion.html#Template-expansion][Org-mode template expansion docs]]

** Linking Notes
   - ~org-roam-insert~
    
   One cool trick is to link to a heading in a note. After the filename add
   ~::*Header Name~.

   #+begin_src
     [[file:note.org::*My heading][Note - My Heading]] 
   #+end_src

* V2
** File links
   - Now uses an ID property.
   - A map of IDs to file paths is stored in ~.org-id-locations~ file, the
     location of which is determined by the variable ~org-id-locations-file~

** Creating and ID manually
   - In the note's buffer, run ~(org-id-get-create)~. This will create a
     properties drawer with the ~:ID:~ property and guuid.
   - Then run ~(org-id-update-id-locations)~. This can also take a file path
     argument. See also https://org-roam.discourse.group/t/how-to-auto-generate-org-id-following-org-roam-find-file-immediate/1412
