#+title: New computer setup
#+date: 2021-09-23 21:22 PM
#+updated: 2021-09-30 17:55 PM
#+roam_tags: shell

A got a new laptop, a System 76 Gazelle with [[https://pop.system76.com][pop_os]]. This was the first I time
used [[https://github.com/apmiller108/dotfiles][my dotfiles]] to setup a Linux box. Previously, I always used MacOS. I want
to keep track of the setup procedure, so next time I wont have to figure some of
this shit out and maybe automate some of it too.

* Setup Git
  I need [[https://github.com/apmiller108/dotfiles][my dotfiles]] so first thing is to get git configured.

** Generate SSH key pair
   - Generate the private/pub key pair
   - Start ~ssh-agent~
   - Add the private key (ie, not the one with ~.pub~) to ~ssh-agent~
    #+begin_src shell
      ssh-keygen -t ed25519 -C "Some Comment"
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/myprivatekey
    #+end_src

** Add SSH Pub key to GitHub account
  Follow [[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account][their instructions]]

** Create symlinks for git dotfiles
   With the SSH key stuff out of the way, I cloned the dotfiles repo.
   After cloning the dotfiles repo create symlinks for:
   - ~.gitconfig~
   - ~.gitignore_global~

   #+begin_src shell
     ln -s ~/dotfiles/git/gitconfig ~/.gitconfig
     ln -s ~/dotfiles/git/gitignore_global ~/.gitignore_global
   #+end_src

* Install ZSH
  #+begin_src shell
  sudo apt-get-update
  sudo apt-get install zsh
  chsh -s $(which zsh)
  sudo reboot
  #+end_src
* Install ohmyzsh
  See https://github.com/ohmyzsh/ohmyzsh
* Create symlink for dotzsh file
* Install fzf
* Install npm and yarn
* Create symlink for dotvimrc file  
* Install Emacs
  Version 28 with native-comp
  Clone the Emacs repo: https://git.savannah.gnu.org/git/emacs.git
  NOTE: At the time of writing this the native-comp branch had already been
  merged into Master.
** Dependencies I needed
   Well, I think I need these...
   - gcc-10
   - libgccjit0
   - libgccjit-10-dev
   - autoconf
   - librsvg2-dev
   - libpng-dev
   - libjpeg-dev
   - imagemagick
   - sqlite3
   - pandoc
   - libcairo2-dev 
** Config and install
   This is how I configured and installed it.
   #+begin_src 
   ./configure --with-modules --with-cairo --with-imagemagick --with-rsvg --with-mailutils --with-native-compilation
   make -j 2
   make install
   #+end_src

   See also https://www.masteringemacs.org/article/speed-up-emacs-libjansson-native-elisp-compilation
