:PROPERTIES:
:ID:       040AE749-B677-4481-A65B-19FB842CE227
:END:
#+title: lsp-mode
#+date: 2021-07-21 08:20 AM
#+updated: 2023-11-18 14:53 PM
#+filetags: :lsp:emacs:

https://emacs-lsp.github.io/lsp-mode/
https://develop.spacemacs.org/layers/+lang/ruby/README.html#language-server-protocol

* Selecting language servers
  If there are multiple installed, the highest priority will win. To select the
  server you want independent of priority you can do this:

  #+begin_src emacs-lisp
  (add-to-list 'lsp-disabled-clients 'ruby-ls) ;; solargraph
  (add-to-list 'lsp-enabled-clients 'ruby-lsp-ls) ;; ruby-lsp (shopify's thing)
  #+end_src
* Typescript
** Setup
   - I choose to use [[https://github.com/theia-ide][theia-ide]] setup. See also https://theia-ide.org/.
     - Requires the [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]] to be installed.
   - Follow the lsp-mode [[https://emacs-lsp.github.io/lsp-mode/page/lsp-typescript/][setup instructions]].
* Ruby
  There are a bunch of options for LSP servers. You can have multiple servers
  and the one used can be specified in a dir-local file
  See also [[https://emacs-lsp.github.io/lsp-mode/page/faq/#i-have-multiple-language-servers-registered-for-language-foo-which-one-will-be-used-when-opening-a-project][emacs-lsp FAQ]]
** Ruby LSP
   https://github.com/Shopify/ruby-lsp

   2023-08-04: I tried it but it didn't appear to have jump to definition or any
   features for that matter.
** Solargraph
   - https://github.com/castwide/solargraph
   - https://solargraph.org/guides

   It doesn't require [[https://yardoc.org/features.html][yard]], but it can help it out.
*** Setup
    Just follow the instructions linked above. For spacemacs, set the ruby-mode
    backend to ~'lsp~
**** Rails
     Use the [[https://github.com/iftheshoefritz/solargraph-rails/][solargraph-rails]] plugin. When using this you'll need to include
     ~"**/*.rb"~ and use the exclude directive in the .solargraph.yml
*** Features
    - autocompletion
    - other things...

    | cmd                          | description                                         |
    |------------------------------+-----------------------------------------------------|
    | lsp-ui-peek-jump-backward    | Moves cursor back to the previous location          |
    | lsp-ui-peek-jump-forward     | Moves cursor back to the next location              |
    | lsp-ui-peek-find-references  | Shows a list of where something is used in the code |
    | lsp-ui-peek-find-definitions | Navigate to definition of thing at point            |
    | lsp-describe-thing-at-point  | Shows documentation                                 |

    - See [[https://develop.spacemacs.org/layers/+tools/lsp/README.html#core-key-bindings][spacemacs core lsp-mode bindings]]
* Vue2
  Install [[https://github.com/vuejs/vetur/tree/master/server][vls]]
** Issues
   When trying to start vls:
   #+begin_src
   Error: Cannot find module 'vscode-css-languageservice/lib/umd/data/browsers'
   #+end_src
* Performance
  I had performance issues with LSP mode, especially with Typescript.

  See https://emacs-lsp.github.io/lsp-mode/page/performance/ for suggestions.

  I increased the ~read-process-output-max~ to 3mb and that seemed to help.

  I was already using emacs v28, so I just rebuild it with native comp. There
  was some pain making the transition, but it completely solved the performance
  issues.

  See https://xenodium.com/emacs-plus-with-native-comp/
  and https://github.com/d12frosted/homebrew-emacs-plus#emacs-27-and-emacs-28-options
