:PROPERTIES:
:ID:       284b93d5-e030-4c8a-932b-03858767dfb6
:END:
#+title: Wine
#+date: 2021-12-05 20:52 PM
#+updated: 2022-05-30 20:23 PM
#+filetags: :linux:

Run Windows programs on linux

* Installing on Ubuntu
  For the latest version. Follow these instructions for your distro
  https://wiki.winehq.org/Ubuntu

  You'll also want [[https://wiki.winehq.org/Winetricks][Winetricks]]
  
* Configuring Wine
  There's a GUI applications for this. Just run ~winecfg~.

** Graphics
   With 4k monitors, the applications will be tiny. Go to the ~Graphics~
   tab and increase the Screen resolution dpi value.

* Installation   
** Installation options
   You can have multiple installation directories. For example, you have run a
   32bit application on a 64bit system by doing something like this:

   #+begin_src shell
   export WINEPREFIX=~/.wine-someapp/
   export WINEARCH="win32"
   wineboot
   #+end_src

   ~WINEPREFIX~ is the directory. See also [[https://wiki.winehq.org/Wine_User%27s_Guide#WINEPREFIX][WINEPREFIX docs]].
   ~WINEARCH~ sets the system architecture
   - ~win32~ or ~win64~

   This will create a ~.wine-someapp/~ directory. With the env vars set, all
   subsequent wine commands will use that directory and architecture. So, now you
   can do ~wine someapp_installer.exe~. Then ~wine ".wine-someapp/drive_c/Program
   Files/someapp/someapp.exe"~

   The env vars will only be set for that terminal sessions. For subsequent
   terminal sessions, they need to be reset or used inline when running the
   command to start the app.
   
   #+begin_src shell
   WINEPREFIX=~/.wine-someapp WINEARCH="win32" wine ~/.wine-someapp/drive_c/Program\ Files/someapp/someapp.exe
   #+end_src
** Desktop shortcuts
   Installing will create desktop shortcuts. Right click on it and choose "Allow
   Launching" to make it clickable.
   
* VST plugins
  See also https://github.com/brendaningram/linux-audio-setup-scripts
  
  - install [[https://github.com/robbert-vdh/yabridge][yabridge]]
  - Add yabridge to your path
  - Create the conventional VST plugin paths on Wine's "C" drive
    #+begin_src  shell
    mkdir -p "$HOME/.wine/drive_c/Program Files/Steinberg/VstPlugins"
    mkdir -p "$HOME/.wine/drive_c/Program Files/Common Files/VST2"
    mkdir -p "$HOME/.wine/drive_c/Program Files/Common Files/VST3"
    #+end_src

  - Add those same paths to yabridge
    #+begin_src shell
    yabridgectl add "$HOME/.wine/drive_c/Program Files/Steinberg/VstPlugins"
    yabridgectl add "$HOME/.wine/drive_c/Program Files/Common Files/VST2"
    yabridgectl add "$HOME/.wine/drive_c/Program Files/Common Files/VST3"
    #+end_src

  - When you download a VST plugin ~exe~ file, right click and run the installer
    with Wine. Make sure it gets installed in one of the paths above.
  - If it's just a DLL file, you should just be able to move it to one of the
    paths above.
  - Sync yabridge ~yabridgectl sync~
  - Check yabridge status ~yabridgectl status~ to verify.
  - The plugin should now be usable in certain DAWs (eg, Reaper).
* Resources
  [[https://wiki.winehq.org/Main_Page][Wine Wiki]]
  [[https://wiki.winehq.org/FAQ][Wine FAQ]]
  [[https://www.winehq.org/documentation][Wine documentation]]
