:PROPERTIES:
:ID:       E5F844B5-1C69-4CD6-B0D8-C785C776CB5C
:END:
#+title: Some SQL things
#+date: 2022-10-06 12:19 PM
#+updated: 2023-10-06 16:01 PM
#+filetags: :sql:postgres

* Join only on first record
  Shameless borrowed from https://www.sisense.com/blog/4-ways-to-join-only-the-first-row-in-sql/

** Correlated subquery
   This loops since the subquery runs once for each record in the outer query

   #+begin_src sql
     select * from users
       join widgets on widgets.id = (
         select id from widgets
         where widgets.user_id = users.id
         order by created_at desc
         limit 1)
   #+end_src

** Complete subquery
*** PostgreSQL ~DISTINCT ON~ with different ~ORDER BY~

   #+begin_src sql
     select * from users
       join (
         select distinct on (user_id) *
           from widgets
           order by user_id, created_at desc)
         as most_recent_user_widgeton on users.id = most_recent_user_widget.user_id
   #+end_src


*** If not using PostgreSQL (ie ~DISTINCT ON~)
    We can use the ~ROW_NUMBER~ function with ordering and selecting the first row.

    See also https://stackoverflow.com/a/49980276

   #+begin_src sql
     select * from users
       join (
         select * from (
             select *, ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY created_at desc) rn
             from widgets) w where w.rn = 1
           ) as most_recent_user_widgeton on users.id = most_recent_user_widget.user_id
   #+end_src

* Date / Time stuff
** Some length of time ago
*** PostgreSQL
    #+begin_src sql
    NOW() - '1 day'::INTERVAL
    #+end_src
*** MSSQL
   #+begin_src sql
    DATEADD(day, -1, GETDATE())
   #+end_src
** Extract date part
*** MSQL
    #+begin_src sql
    SELECT DATEPART(MINUTE, CURRENT_TIMESTAMP)
    #+end_src
** Convert Datetime to Date
*** MSSQL
   #+begin_src sql
   SELECT DATEADD(dd, 0, DATEDIFF(dd, 0, GETDATE()))
   #+end_src

   OR

   #+begin_src sql
   SELECT CONVERT(DATE, GETDATE())
   #+end_src
* JSON
** bytea
   If you need to insert into a ~bytea~ column, one approach would be to hexdump
   the file the insert the it using the ~convert~ utility.

   #+begin_src shell
   xxd -ps /path/to/json | tr -d '\n' | pbcopy
   #+end_src

   #+begin_src sql
   update sometable set "json" = convert('PASTE_HEXDUMP_FROM_ABOVE_STEP_HERE', 'hex') where id = 1
   #+end_src
* Schema comments
  - Comments can be added to any database object.
  - Only one comment allowed per object.
  - To remove a comment, just replace the comment with NULL

** Add a comment to a Table
   #+begin_src sql
     COMMENT ON TABLE horsey_coconuts IS 'Coconuts in Mercia';
   #+end_src

   View with
   #+begin_src shell
     \dt+ table_name
   #+end_src

** Add comments to a column
   #+begin_src sql
     COMMENT ON COLUMN horsey_coconuts.swallow_speed IS 'The air speed the swallow who carried the coconut';
   #+end_src

   View with
   #+begin_src shell
     \d+ table_name
   #+end_src
* CTE (with query)
** Use case 1: data migrations
   Store deleted records in a temp table in case something needs to be rolled
   back. Return ~*~ from the delete operation which populates the CTE.

   #+begin_src sql
  WITH deletes AS (
    DELETE FROM widgets WHERE widget_type_id IN (
      SELECT id FROM widget_types wt WHERE wt.name= 'shiny'
    )
    RETURNING *
  )
  SELECT *
    INTO temp_delete_widgets_20230627
    FROM deletes;
   #+end_src
* Constraints (PG)
  See also [[id:A3972BA3-6BD6-4970-8B22-0065A1F7978D][ActiveRecord Migrations Cheatsheet]] for some stuff on ~CHECK~
  constraints

  See also https://www.crunchydata.com/blog/postgres-constraints-for-newbies as
  an easy to read reference on PG constraints

** deferring constraints
   Some constraints support deferrability (checks do not)

   Some use cases you might want to only perform the check at the end of the
   transaction. Use ~DEFERABLE~ for this.

   #+begin_src sql
    alter table things add constraint foo_unique (foo) deferrable
   #+end_src

   Or you can defer constraints on demand within a transaction. See also
   https://www.postgresql.org/docs/16/sql-set-constraints.html

   See also https://hashrocket.com/blog/posts/deferring-database-constraints for
   more advanced example
