:PROPERTIES:
:ID:       B31DB651-BC64-41FB-9E28-6AEEF933F186
:END:
#+title: Programming posts of interest
#+date: 2022-02-03 10:56 AM
#+updated: 2024-02-12 08:20 AM
#+filetags: :ruby:javascript:sql:typescript:emacs

This is list a list of programming articles that I find interesting and may want
to reference again in the future. For now I'm going to organize them by language
and/or framework.

* Ruby
  - [[https://longliveruby.com/articles/build-your-own-concurrency-control-in-sidekiq][Build concurrency control in Sidekiq]]:
    This tutorial article shows how one can leverage Redis to lock resources.
    It's context is locking Sidekiq jobs, but it would be easily repurposed to
    lock anything. Also, worth noting, the paid version of Sidekiq (Sidekiq ENT)
    already has a [[https://github-wiki-see.page/m/mperham/sidekiq/wiki/Ent-Unique-Jobs][unique_for option]]. The general pattern/algorithm this article
    demonstrates is also discussed in the [[https://redis.io/topics/distlock][Distributed locks with Redis docs]].
  - [[https://www.speedshop.co/2017/10/12/appserver.html][Configuring Puma, Unicorn and Passenger for Maximum Efficiency]]:
    Shares advice for figuring out how many workers and threads to use for your
    server configuration based on available CPU and memory resources. For
    example worker_count = 1.5 x (n hyperthreads). There's also an explanation
    of forking and copy-on-write.
    - [[https://shopify.engineering/ruby-execution-models][To Thread or Not to Thread: An In-Depth Look at Ruby’s Execution Models]]
      Is another look along the same lines, but favors forking processes over
      spawning threads. It shows how CoW memory works and how to inspect metrics
      related to it.
  - [[https://blog.appsignal.com/2018/05/29/ruby-magic-enumerable-and-enumerator.html][Ruby's magical Enumerable module]]:
    Shows how to make objects enumerable by creating a ~LinkedList~ class. See
    also [[id:fcba0c10-cdb7-4d98-96ad-acf6afafe275][Make something enumerable]] for another example.
  - [[https://blog.arkency.com/dont-waste-your-time-on-assets-compilation-on-heroku/][Don't waste your time on assets compilation on Heroku]]: A silly, click-baity
    title, but an interesting take on piping Rails assets to a CDN.
  - [[https://www.shalerb.org/][Shale]]: This isn't a post, but a library for object mapping and
    serialization. It looks promising.
  - [[https://evilmartians.com/chronicles/gemfile-of-dreams-libraries-we-use-to-build-rails-apps][Gemfile of dreams: Libraries we use to build rails apps]]: Evil Martians'
    commonly uses Rails libs.
  - https://semaphoreci.com/blog/ruby-webassembly: How to webassembly in Ruby as
    of February, 2023.
  - [[https://www.driftingruby.com/episodes/deploying-with-mrsk][Drifting Ruby: Deploying with MRSK]]
    Screen cast of deploying with docker to Digital Ocean using [[https://github.com/mrsked/mrsk][MRSK]]. There's a
    bunch of gotchas to set this up, so worth a watch. This can be used for
    deploying pretty much anywhere, even on prem. Servers need to be prepared in
    advance (eg, load balancer, app nodes, database server, etc.)
  - https://stanko.io/deconstructing-action-cable-DC7F33OsjGmK
    This is an explanation of how ActionCable works. There's some information in
    here that might help demystify some things or at least reveal details not in
    the [[https://guides.rubyonrails.org/action_cable_overview.html][official guide.]]
* Javascript
  - https://www.akshaykhot.com/using-hotwire-without-rails/: Explains how to use
    Hotwire (Turbo primarily) without the RoR framework. What's nice about this
    is that it becomes very clear what Turbo is all about.
* DevOps
  - [[https://railsnotes.xyz/blog/deploying-ruby-on-rails-with-dokku-redis-sidekiq-arm-docker-hetzner][Deploying Ruby on Rails with Dokku]]: this is a kinda of ultimate guide for
    using Dokku. Includes deploying with docker.
