:PROPERTIES:
:ID:       a0628dc3-e296-43ae-9830-d25fdc33659c
:END:
#+title: pipewire
#+date: 2022-11-29 13:59 PM
#+updated: 2023-01-29 17:10 PM
#+filetags: :linux:audio:

https://docs.pipewire.org/index.html

* GUI
  [[https://gitlab.freedesktop.org/rncbc/qpwgraph][qpwgraph]] works just like qjackctl
* Scripting
  See https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Migrate-JACK
** pw-link
   Manage IO connections. Takes the place of ~jack_connect~, ~jack_disconnect~
   and ~jack_lsp~
* Issues
** Volume very low
*** Set volume using a mixer tool
**** alsamixer
   Use ~alsamixer~ tool and set the output gain to whatever.

   - See also https://wiki.archlinux.org/title/PipeWire#Low_volume
   - You can store the alsa config by using ~alsactl~

     #+begin_src shell
     sudo alsactl store
     #+end_src
**** pavucontrol
   Pipewire works with Pulse audio, so pavucontrol should work as well. In fact,
   I had better luck with this to set the volume level my Xone k2
**** amixer
     Like alsamixer, but CLI only (no TUI)
* Multiple sound cards
  By default pipewire handles multiple sound cards timing by resampling. In
  pavucontrol you can set the Pro Audio profile on the card which, amonng other
  things will assume all devices share the same clock.

  https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#what-is-the-pro-audio-profile

** Timing
   Instead of letting pipewire handle timing by resampling, which I found to be
   less than perfect, we can use a module-loopback to introduce a delay on one
   or more devices.

   See also [[id:959acd5a-c6f7-4247-baf6-d8f5c7fd765a][pulseaudio]] for how to set that up
