:PROPERTIES:
:ID:       6A08F445-6C81-4C71-BBA6-6974CABFD0CE
:END:
#+title: Ruby gems
#+date: 2023-10-13 13:46 PM
#+updated:  2024-10-11 09:36 AM
#+filetags: :ruby:

This is a list of potentially useful Ruby libraries.

See also
- https://github.com/markets/awesome-ruby
- https://evilmartians.com/chronicles/gemfile-of-dreams-libraries-we-use-to-build-rails-apps

* Background jobs
** whenever
   Create cron jobs that can run rail runner, rake or shell commands using nice
   ruby syntax
   https://github.com/javan/whenever
** schked
   Like whenever
   https://github.com/bibendi/schked
** sidekiq-limit_fetch
   https://github.com/deanpcmad/sidekiq-limit_fetch
** sidekiq-unique-job
   Unique jobs is a sidekiq ENT feature. Use this instead if you can't buy it.
   https://github.com/mhenrixon/sidekiq-unique-jobs
** sidekiq-cron
   https://github.com/sidekiq-cron/sidekiq-cron
* Database
** active_record_doctor
   https://github.com/gregnavis/active_record_doctor
** database_consistency
   https://github.com/djezzzl/database_consistency
** fx
   Versioned database functions
   https://github.com/teoljungberg/fx
** postgresql_cursor
   Leverage [[https://www.postgresql.org/docs/16/plpgsql-cursors.html][PG's cursor]] feature as an alternative to find_each / find_in_batches
   https://github.com/afair/postgresql_cursor
** scenic
   Versioned database views
   https://github.com/scenic-views/scenic
** strong_migrations
   https://github.com/ankane/strong_migrations
** store_attribute
   Type casting for store accessors
   https://github.com/palkan/store_attribute
* Debugging
** trace_location
   Uses TracePoint to log source locations of method calls for a given operation
   https://github.com/yhirano55/trace_location
* Serialization
** [[https://www.shalerb.org/][Shale]]
   A library for object mapping and serialization. It looks promising.
* Dates, Time and Schedules
** ice_cube
   Scheduling
   https://github.com/ice-cube-ruby/ice_cube
