:PROPERTIES:
:ID:       4D90F42B-B4DA-4CDA-9885-B8FF372FDB72
:END:
#+title: psql
#+date: 2023-09-22 12:38 PM
#+updated:  2023-12-13 10:58 AM
#+filetags: :postgres:

See also [[id:CD58C290-AF97-4882-98D9-2FCC7B61763E][postgresql.conf]]
See also [[id:D111FFA2-4A9D-41F4-87DC-E59F3D6E8564][Row locking]]

* Authentication
  There are several methods.
  See also https://stackoverflow.com/a/6524167
** Using env vars
   - ~PGUSER~
   - ~PGPASSWORD~
* .psqlrc
  To me the most important one is ~\pset null '(null)'~ in order to distinguish
  between empty string and null.

  See also
   - https://github.com/apmiller108/dotfiles/blob/master/psql/psqlrc
   - https://thoughtbot.com/blog/an-explained-psqlrc
* Logs
** Where are the logs?
   See also https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-WHERE
   #+begin_src sql
     SHOW log_destination;
   #+end_src

   #+begin_src
    log_destination
    -----------------
    stderr
    (1 row)
   #+end_src

   stderr is default, but other options are available. See docs above.
   There is also a log collector that will capture log entries and write to a
   file. So determine if logs are being collected:

   #+begin_src sql
     SHOW log_collector;
   #+end_src

   #+begin_src
   logging_collector
   -------------------
   on
   (1 row)
   #+end_src

   If the log collector isn't on, see [[id:CD58C290-AF97-4882-98D9-2FCC7B61763E][postgresql.conf]] for how to turn it on.
   If the collector is on, find the current collection file with:

   #+begin_src sql
    SELECT pg_current_logfile();
   #+end_src

   This will print a path relative to the data directory. To find the location
   of the data directory:

   #+begin_src sql
    SHOW data_directory;
   #+end_src

   Putting those two things together, you can tail the logs.

* Meta commands
** \c
   ...followed by the database name to connect to it.
** \dx
   list installed extensions
** \dv
   list views
** \g
   Run the last command. Also use up arrow enter.
** \l
   List the databases on the server
** \o
   ...followed by a filename, to toggle writing query output to that file.
** \pset format wrapped
   Turn on wrapping of the results
** \s
   Prints history of commands run previously.
   TIP: ~ctrl r~ "reverse search" is available
** \timing
   Toggles timing which prints the time each command takes
** \x
   Expanded display to make output more readable
* Restore a dump
  See also
   - [[id:A7B098E7-2E2E-48C8-9553-48E08727FA38][pg_dump]]
   - https://www.postgresql.org/docs/current/backup-dump.html#BACKUP-DUMP-RESTORE

  #+begin_src
  psql --set ON_ERROR_STOP=on --quiet \
    --no-psqlrc \
    --output /dev/null \
    dbname \
    --file database_dump.sql
  #+end_src
* System catalog tables
  - These are tables that begin with ~pg_*~ (use tab completion to see the list)
  - ~SELECT * FROM~ these tables to get system information.
  Here's just a few for reference:
** pg_extension
   Contains installed extensions
** pg_stat_activity
   Database activity. This will show the ~pid~ of the activity owner. Use the ~pid~
   to cancel or terminate queries.
** pg_locks
* Terminate queries
  Find the pid by querying ~pg_stat_activity~, then...
  - ~SELECT pg_cancel_backend(pid)~ (graceful)
  - ~SELECT pg_terminate_backend(pid)~
* Transactions
  Do things in transactions and validate them before committing them. Use
  rollback when things get weird.
  #+begin_src sql
  BEGIN;

  -- Insert, update, modify schema, or whatever
  -- Verify it worked. If it didn't Use `ROLLBACK;`.

  COMMIT;
  #+end_src
* Miscellaneous
** PG_BACKEND_PID()
   ~psql~ process ID
   #+begin_src sql
     SELECT PG_BACKEND_PID();
   #+end_src
** Find PostgreSQL config file
   This will print the file path to the config file.
   #+begin_src sql
    SHOW config_file;
   #+end_src
  See also [[id:CD58C290-AF97-4882-98D9-2FCC7B61763E][postgresql.conf]]
** Find the data directory
   #+begin_src sql
    SHOW data_directory;
   #+end_src
* Scripting
  Commands can be passed to ~psql~ using the ~-c~ switch, which outputs the results
  to stdout

  #+begin_src shell
    psql -h database -d myapp_development -c "select * from users" > results
  #+end_src

  Use the ~-f~ followed by a file path to run commands from a file.

  #+begin_src shell
    psql -f insert_widgets.sql
  #+end_src
