:PROPERTIES:
:ID:       7FAFD333-0739-4A07-BC34-DC1D6E224F49
:END:
#+title: Attention Parasites
#+date: 2025-09-11 08:19 AM
#+updated:  2025-09-11 11:30 AM
#+filetags: :philosophy:

There is a monster, not of flesh and blood, but of algorithms, addiction and
cruel incentives, feeding on the neurochemical impulses of human attention like
a slot machine designed by sociopathic ideologues. It's minions are the digital
carnies running a rigged game at a grotesque carnival of human misery. They've
discovered that *outrage is the new opium*, and they're dealing it by the gig to
anyone with an internet connection.

Human attention is the commodity. It must be captured by any means to keep
eyeballs on the ads so these hustlers and their sponsors can profit. Everybody
wins, except you, who descends ever deeper into madness.

- Sense making is too hard to produce and too boring
- Lies are cheap and entertaining
- Anger is more engaging than joy
- Fear pays better than courage

This is the playbook. And now, we're drowning in...

- Righteous indignation
- Half-truths
- Complete fabrications
- Anxiety
- Delusion

"Oh but not me! I know what's up. I know the truth. You see, I'm in this special
group and I've got the inside scoop.". I've got bad news for you. Everyone, has
been indoctrinated into a special group with the apparent inside scoop. You're
in an algorithmically curated echo chamber fueled by greedy grifters, Big Tech
profiteering, and human frailty. Sorry about that.

But, it's happened to all of us.

There are many bad actors here. Attention Parasites with incurving hooks digging
to our soft, vulnerable brain matter, ever feeding on what little sense of well
being we have left. But we too are complicit.

We've created a system that rewards the worst impulses of human nature.
Manufactured outrage and dubious information makes content creators and media
platforms richer. Moments of authentic human connection are sacrificed to a
digital rage machine, ground up and spit up to sell yet more ad space.

/And the hideous irony of it all?/

*We’re paying them to destroy us*. Every video watched, Every ad viewed, every
subscription purchased, every premium account activated, every weird green
health drink sold, is another vote for chaos, another investment in the
systematic dismantling of our sense of shared reality.

Welcome to the freak show, folks. The cost of admission is your sanity. So pay
up or else.

Or else what? How about...

- Recognize the poison in the information landscape.
- Recognize the tendency towards tribalism in our ape brains and it's assault on
  reason.
- Recognize how partisanism and group think destroys sense making.
- Delete social media accounts.
- Be informed, but don't let anyone tell you how to feel.
- Think about problems from first principles.

By the way, *we're all in this together*. Don't forget that. It might be the most
important part of all this.

AM
