name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: build_site
        run: |
          echo Starting build step...
          sudo add-apt-repository ppa:kelleyk/emacs
          sudo apt-get update
          sudo apt-get install emacs27
          echo `emacs --version`
          emacs -Q --batch -l ./publish.el --funcall my/publish
          cp -r site_assets/* public/
      - name: deploy_site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          npm_config_user: "root"
        run: |
          echo Starting deploy step...
          echo Installing dependencies...
          sudo npm install netlify-cli -g --unsafe-perm=true
          echo Deploying to netlify...
          netlify deploy --dir=public --prod


